name: Deploy to GitHub Pages with Custom Config

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Modify vite.config.js for deployment
      - name: Update vite.config.js for deployment
        run: |
          sed -i 's|base:.*|base: "/aio/",|' vite.config.js

      # Step 4: Commit changes to a new branch
      - name: Create deployment branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b gh-pages-config
          git add vite.config.js
          git commit -m "Update vite.config.js for GitHub Pages deployment"
          git push --force origin gh-pages

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout deployment branch
      - name: Checkout deployment branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages-config

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies and build
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
